Introduce the "pre-second pass" pass
It shortens the second pass by syncing files that will only be needed
after the new indexes are deployed.

diff --git a/bin/ftpsync b/bin/ftpsync
--- a/bin/ftpsync
+++ b/bin/ftpsync
@@ -284,6 +284,8 @@ RSYNC_BW=${RSYNC_BW:-0}
 RSYNC_OPTIONS=${RSYNC_OPTIONS:-"-prltvHSB8192 --timeout 3600 --stats ${RSYNC_FILTER}"}
 # Options we only use in the first pass, where we do not want packages/sources to fly in yet and don't want to delete files
 RSYNC_OPTIONS1=${RSYNC_OPTIONS1:-"--exclude Packages* --exclude Sources* --exclude Release* --exclude InRelease --exclude ls-lR*"}
+# Options for pass previous to the "second" pass, where we get new index files
+RSYNC_OPTIONSpre2=${RSYNC_OPTIONSpre2:-"--ignore-existing --fuzzy"}
 # Options for the second pass, where we do want everything, including deletion of old and now unused files
 RSYNC_OPTIONS2=${RSYNC_OPTIONS2:-"--max-delete=40000 --delay-updates --delete --delete-after --delete-excluded"}
 # Which rsync share to use on our upstream mirror?
@@ -487,6 +489,20 @@ while [ -e "${UPDATEREQUIRED}" ]; do
 
     # if we want stage2 *or* all
     if [ "xtruex" = "x${SYNCSTAGE2}x" ] || [ "xtruex" = "x${SYNCALL}x" ]; then
+        log "Running pre-stage2: ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONSpre2} ${EXCLUDE} ${SOURCE_EXCLUDE} ${RSYNCPTH}::${RSYNC_PATH} ${TO}"
+
+        set +e
+        # We are lucky, it worked. Now do pre step 2 and sync again
+        ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONSpre2} ${EXCLUDE} ${SOURCE_EXCLUDE} \
+            ${RSYNCPTH}::${RSYNC_PATH} "${TO}" >>"${LOGDIR}/rsync-${NAME}.log" 2>>"${LOGDIR}/rsync-${NAME}.error"
+        result=$?
+        set -e
+
+        log "Back from rsync with returncode ${result}"
+
+        # We don't care if it failed or if it succeeded, we will redo
+        # whatever failed
+
         log "Running stage2: ${RSYNC} ${RSYNC_OPTIONS} ${RSYNC_OPTIONS2} ${EXCLUDE} ${SOURCE_EXCLUDE} ${RSYNCPTH}::${RSYNC_PATH} ${TO}"
 
         set +e
