ftpsync
lockfile in shell, for procmail haters
Signed-off-by: Joerg Jaspert <joerg@debian.org>

diff --git a/bin/ftpsync b/bin/ftpsync
--- a/bin/ftpsync
+++ b/bin/ftpsync
@@ -327,9 +327,18 @@ mkdir -p "${TO}/project/trace"
 touch "${UPDATEREQUIRED}"
 
 # Check to see if another sync is in progress
-if ${LOCKFILE} -! -l 43200 -r 0 "${LOCK}"; then
+if [ -x "${LOCKFILE}" ]; then
+	if ${LOCKFILE} -! -l 43200 -r 0 "${LOCK}"; then
         error "Unable to start rsync, lock file still exists"
         exit 1
+	fi
+else
+	if [ "`find ${LOCK} -maxdepth 1 -cmin -720`" != ""]; then
+        error "Unable to start rsync, lock file still exists"
+        exit 1
+	else
+		touch "${LOCK}"
+	fi
 fi
 trap cleanup EXIT ERR TERM HUP INT QUIT
 
